server {
    listen 80;         # На каком порту внутри контейнера Nginx ждет людей (80 — стандарт для HTTP)
    server_name localhost;

    # БЛОК 1: Что делать, если пользователь зашел на сайт (например, mysite.com/)
    location / {
        root /usr/share/nginx/html;       # Где физически лежат файлы Vue внутри контейнера
        index index.html index.htm;        # Какой файл открывать по умолчанию
        
        # Самая важная строка для Vue-router:
        try_files $uri $uri/ /index.html; 
    }

    # БЛОК 2: Что делать, если фронтенд делает запрос к бэкенду (например, mysite.com/api/users)
    location /api/ {
        proxy_pass http://backend:8000/;  # Перенаправляем запрос в контейнер с FastAPI
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}